### ISSUE TITLE
fknsrs.biz/p imports

### ISSUE THREAD

**Issue by scorredoira** [deoxxa/ottoext#1]
Hi,

Shouldn't you update the imports fknsrs.biz/p/ to github.com/deoxxa?

**Comment by deoxxa** [comment]
Nope, I have my go projects namespaced under my own domain on purpose. Is there a reason you think I should change them?

**Comment by scorredoira** [comment]
I found this repo from a comment of yours about adding setTimeout, but if you do a "go get github.com/deoxxa/ottoext" it throws compile errors. Maybe you can include in the readme to install it with "go get fknsrs.biz/p/ottoext" instead of from github.

**Comment by deoxxa** [comment]
Well, I never refer to it as `github.com/deoxxa/ottoext` - I make sure whenever I link to it, I link to its proper name. How did you end up installing it as `github.com/deoxxa/ottoext`?

**Comment by scorredoira** [comment]
I see what happened: if you click to view the source in https://godoc.org/fknsrs.biz/p/ottoext it redirects to the github repo. From there I copied from the url to give it a try.
